#!/bin/bash

source ./smb/var
source ./smb/functions
source ./msfvenom/var
source ./msfvenom/function
source ./wordpress/var
source ./wordpress/functions

    PS3='Please enter your choice: '
    func=("smb" "msfvenom" "smbserver" "wordpress" "Quit")
    select opt in "${func[@]}"
    do
        case $opt in
            "smb")
                smb
                ;;
            "msfvenom")
                msfv
                ;;
            "smbserver")
                smbserver.py share .
                ;;
            "wordpress")
                wp
                ;;
            "Quit")
                break
                ;;
            *) echo "invalid option $REPLY";;
        esac
    done