#!/bin/bash

function smb {

    source ./var

    PS3='Please enter your choice: '
    options=("smblogin" "smbenum" "smbserver" "Quit")
    select opt in "${options[@]}"
    do
        case $opt in
            "smblogin")
                smbclient -U "${smb_user}%${smb_pass}" //$smb_ip/<location>
                ;;
            "smbmap")
                smbmap -HR $smb_ip
                ;;
            "smbserver")
                smbserver.py share .
                ;;
            "Quit")
                break
                ;;
            *) echo "invalid option $REPLY";;
        esac
    done
}

    PS3='Please enter your choice: '
    func=("smb" "smbenum" "smbserver" "Quit")
    select opt in "${func[@]}"
    do
        case $opt in
            "smb")
                smb
                ;;
            "smbmap")
                smbmap -HR $smb_ip
                ;;
            "smbserver")
                smbserver.py share .
                ;;
            "Quit")
                break
                ;;
            *) echo "invalid option $REPLY";;
        esac
    done